apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: helloworld
  project: default
  source:
    path: .
    helm:
      values: |
        pushgateway:
          enabled: false
    repoURL: https://github.com/Kcwan18/test-helm
    targetRevision: '@deploy/develop'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true