apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-helm
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 10.1.21.70:443
    namespace: hello-world
  project: default
  source:
    # chart: helloworld-chart
    path: .
    helm:
      values: |
        pushgateway:
          enabled: false
    repoURL: https://github.com/Kcwan18/test-helm
    targetRevision: '@deploy/develop'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 