apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-helm2
  namespace: argocd-ns
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://8.210.137.227:6443
    namespace: hello-world2
  project: default
  source:
    path: .
    helm:
      values: |
        pushgateway:
          enabled: false
    repoURL: https://github.com/Kcwan18/test-ksvc-helm
    targetRevision: 'main'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 